// Mock song data
export const MOCK_SONGS = [
  {
    id: '1',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: 202,
    cover: 'https://picsum.photos/seed/song1/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    liked: true,
  },
  {
    id: '2',
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: 203,
    cover: 'https://picsum.photos/seed/song2/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    liked: false,
  },
  {
    id: '3',
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    album: 'Stay',
    duration: 141,
    cover: 'https://picsum.photos/seed/song3/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    liked: true,
  },
  {
    id: '4',
    title: 'Heat Waves',
    artist: 'Glass Animals',
    album: 'Dreamland',
    duration: 238,
    cover: 'https://picsum.photos/seed/song4/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    liked: false,
  },
  {
    id: '5',
    title: 'As It Was',
    artist: 'Harry Styles',
    album: "Harry's House",
    duration: 167,
    cover: 'https://picsum.photos/seed/song5/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    liked: true,
  },
  {
    id: '6',
    title: 'Anti-Hero',
    artist: 'Taylor Swift',
    album: 'Midnights',
    duration: 200,
    cover: 'https://picsum.photos/seed/song6/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    liked: false,
  },
  {
    id: '7',
    title: 'Flowers',
    artist: 'Miley Cyrus',
    album: 'Endless Summer Vacation',
    duration: 200,
    cover: 'https://picsum.photos/seed/song7/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3',
    liked: true,
  },
  {
    id: '8',
    title: 'Unholy',
    artist: 'Sam Smith ft. Kim Petras',
    album: 'Gloria',
    duration: 156,
    cover: 'https://picsum.photos/seed/song8/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3',
    liked: false,
  },
  {
    id: '9',
    title: 'Golden Hour',
    artist: 'JVKE',
    album: 'this is what ____ feels like',
    duration: 210,
    cover: 'https://picsum.photos/seed/song9/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3',
    liked: true,
  },
  {
    id: '10',
    title: 'Calm Down',
    artist: 'Rema & Selena Gomez',
    album: 'Rave & Roses Ultra',
    duration: 239,
    cover: 'https://picsum.photos/seed/song10/300/300',
    audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3',
    liked: false,
  },
]

export const MOCK_PLAYLISTS = [
  {
    id: 'liked',
    name: 'Liked Songs',
    type: 'playlist',
    cover: null,
    gradient: 'from-indigo-900 to-purple-900',
    songs: MOCK_SONGS,
    owner: 'You',
  },
  {
    id: 'p1',
    name: 'Daily Mix 1',
    type: 'playlist',
    cover: 'https://picsum.photos/seed/pl1/300/300',
    description: 'The Weeknd, Dua Lipa, Harry Styles and more',
    songs: MOCK_SONGS.slice(0, 5),
    owner: 'Spotify',
  },
  {
    id: 'p2',
    name: 'Chill Mix',
    type: 'playlist',
    cover: 'https://picsum.photos/seed/pl2/300/300',
    description: 'Lo-fi beats to relax and study',
    songs: MOCK_SONGS.slice(2, 7),
    owner: 'Spotify',
  },
  {
    id: 'p3',
    name: 'Workout Hits',
    type: 'playlist',
    cover: 'https://picsum.photos/seed/pl3/300/300',
    description: 'High energy tracks for your workout',
    songs: MOCK_SONGS.slice(1, 6),
    owner: 'Spotify',
  },
  {
    id: 'p4',
    name: 'Late Night Drive',
    type: 'playlist',
    cover: 'https://picsum.photos/seed/pl4/300/300',
    description: 'Perfect vibes for night drives',
    songs: MOCK_SONGS.slice(3, 8),
    owner: 'You',
  },
  {
    id: 'p5',
    name: 'Top Hits 2024',
    type: 'playlist',
    cover: 'https://picsum.photos/seed/pl5/300/300',
    description: "The year's biggest tracks",
    songs: MOCK_SONGS,
    owner: 'Spotify',
  },
]

export const MOCK_ALBUMS = [
  {
    id: 'a1',
    name: 'After Hours',
    artist: 'The Weeknd',
    type: 'album',
    year: 2020,
    cover: 'https://picsum.photos/seed/alb1/300/300',
    songs: MOCK_SONGS.slice(0, 4),
  },
  {
    id: 'a2',
    name: 'Future Nostalgia',
    artist: 'Dua Lipa',
    type: 'album',
    year: 2020,
    cover: 'https://picsum.photos/seed/alb2/300/300',
    songs: MOCK_SONGS.slice(1, 5),
  },
  {
    id: 'a3',
    name: 'Midnights',
    artist: 'Taylor Swift',
    type: 'album',
    year: 2022,
    cover: 'https://picsum.photos/seed/alb3/300/300',
    songs: MOCK_SONGS.slice(2, 6),
  },
  {
    id: 'a4',
    name: 'Dreamland',
    artist: 'Glass Animals',
    type: 'album',
    year: 2020,
    cover: 'https://picsum.photos/seed/alb4/300/300',
    songs: MOCK_SONGS.slice(3, 7),
  },
  {
    id: 'a5',
    name: "Harry's House",
    artist: 'Harry Styles',
    type: 'album',
    year: 2022,
    cover: 'https://picsum.photos/seed/alb5/300/300',
    songs: MOCK_SONGS.slice(4, 8),
  },
]

export const MOCK_ARTISTS = [
  { id: 'ar1', name: 'The Weeknd', type: 'artist', cover: 'https://picsum.photos/seed/art1/300/300', followers: '108M' },
  { id: 'ar2', name: 'Dua Lipa', type: 'artist', cover: 'https://picsum.photos/seed/art2/300/300', followers: '79M' },
  { id: 'ar3', name: 'Taylor Swift', type: 'artist', cover: 'https://picsum.photos/seed/art3/300/300', followers: '115M' },
  { id: 'ar4', name: 'Harry Styles', type: 'artist', cover: 'https://picsum.photos/seed/art4/300/300', followers: '65M' },
  { id: 'ar5', name: 'Miley Cyrus', type: 'artist', cover: 'https://picsum.photos/seed/art5/300/300', followers: '52M' },
  { id: 'ar6', name: 'Glass Animals', type: 'artist', cover: 'https://picsum.photos/seed/art6/300/300', followers: '18M' },
]

export const GENRE_CARDS = [
  { id: 'g1', name: 'Pop', color: '#1e3264', textColor: '#fff' },
  { id: 'g2', name: 'Hip-Hop', color: '#7358ff', textColor: '#fff' },
  { id: 'g3', name: 'R&B', color: '#006450', textColor: '#fff' },
  { id: 'g4', name: 'Dance/Electronic', color: '#e8115b', textColor: '#fff' },
  { id: 'g5', name: 'Indie', color: '#8d67ab', textColor: '#fff' },
  { id: 'g6', name: 'Rock', color: '#ba5d07', textColor: '#fff' },
  { id: 'g7', name: 'Jazz', color: '#503750', textColor: '#fff' },
  { id: 'g8', name: 'Classical', color: '#1e3264', textColor: '#fff' },
  { id: 'g9', name: 'K-Pop', color: '#e8115b', textColor: '#fff' },
  { id: 'g10', name: 'Latin', color: '#e55d25', textColor: '#fff' },
  { id: 'g11', name: 'Metal', color: '#148a08', textColor: '#fff' },
  { id: 'g12', name: 'Country', color: '#8d67ab', textColor: '#fff' },
]

export const HOME_QUICK_ACCESS = [
  { id: 'liked', name: 'Liked Songs', gradient: 'from-indigo-600 to-blue-400', route: '/collection/tracks' },
  { id: 'p1', name: 'Daily Mix 1', cover: 'https://picsum.photos/seed/pl1/300/300', route: '/playlist/p1' },
  { id: 'p2', name: 'Chill Mix', cover: 'https://picsum.photos/seed/pl2/300/300', route: '/playlist/p2' },
  { id: 'p3', name: 'Workout Hits', cover: 'https://picsum.photos/seed/pl3/300/300', route: '/playlist/p3' },
  { id: 'a1', name: 'After Hours', cover: 'https://picsum.photos/seed/alb1/300/300', route: '/album/a1' },
  { id: 'p5', name: 'Top Hits 2024', cover: 'https://picsum.photos/seed/pl5/300/300', route: '/playlist/p5' },
]